# appveyor.yml
---
branches:
  only:
    - master

environment:
  access_token:
    secure: oZKFgPgc7mmfMPDsnGfifLxZx/6CcErYTzKZCpmcwjlPybJeovJuZt4P+Wl3hPbs
  
  matrix:
  - TOXENV: py36
    PYTHON: "C:\\Python36-x64"
  
init:
  - "ECHO %TOXENV%"
  
build:
  off

install:
- "SET PATH=%PYTHON%; %PYTHON%\\Scripts; %PATH%"
- "%PYTHON%\\python -m pip install -U pip"
- pip install tox

test_script:
- tox

on_success:
- "SET PATH=%PYTHON%; %PYTHON%\Scripts; %PATH%"
- "%PYTHON%\\Scripts\pip install -r requirements.txt"
- "%PYTHON%\\python covid_19\nl_routines.py"
- git config --global credential.helper store
- ps: Add-Content -Path "$HOME\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline
- git config --global user.email "32603156+rogerlord@users.noreply.github.com"
- git config --global user.name "rogerlord"
- git add -Af ./data
- git commit .\data\
- git push --all