# appveyor.yml
---
branches:
  only:
    - master

environment:
  matrix:
  - TOXENV: py36
    PYTHON: "C:\\Python36-x64"
  
init:
  - "ECHO %TOXENV%"
  
build:
  off

install:
- "SET PATH=%PYTHON%; %PYTHON%\\Scripts; %PATH%"
- python -m pip install -U pip
- pip install tox

test_script:
- tox