# appveyor.yml
---
branches:
  only:
    - master

environment:
  access_token:
    secure: oZKFgPgc7mmfMPDsnGfifLxZx/6CcErYTzKZCpmcwjlPybJeovJuZt4P+Wl3hPbs
  
  matrix:
  - TOXENV: py36
    PYTHON: "C:\\Python36-x64"
  
init:
  - "ECHO %TOXENV%"
  
skip_commits:
  author: AppVeyor
  
build:
  off

install:
- "SET PATH=%PYTHON%; %PYTHON%\\Scripts; %PATH%"
- "%PYTHON%\\python -m pip install -U pip"
- "%PYTHON%\\Scripts\\pip install tox"

test_script:
- tox

on_success:
- "SET PATH=%PYTHON%; %PYTHON%\\Scripts; %PATH%"
- "%PYTHON%\\Scripts\\pip install -r requirements.txt"
- "%PYTHON%\\python covid_19\\nl_routines.py .\\"
- ps: gitcommit.ps1
