# appveyor.yml
---
branches:
  only:
    - master

environment:
  access_token:
    secure: oZKFgPgc7mmfMPDsnGfifLxZx/6CcErYTzKZCpmcwjlPybJeovJuZt4P+Wl3hPbs
  
  matrix:
  - TOXENV: py36
    PYTHON: "C:\\Python36-x64"
    MINICONDA: "C:\\Miniconda36-x64"
  
init:
  - "ECHO %TOXENV%"
  
skip_commits:
  author: AppVeyor
  
build:
  off

install:
- "%PYTHON%\\python -m pip install -U pip"
- "%PYTHON%\\Scripts\\pip install tox"

test_script:
- "%PYTHON%\\Scripts\\tox"

on_success:
- "SET PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
- ps: |
    $currentThread = [System.Threading.Thread]::CurrentThread
    $culture = [CultureInfo]::InvariantCulture.Clone()
    $culture.DateTimeFormat.ShortDatePattern = 'yyyy-MM-dd'
    $currentThread.CurrentCulture = $culture
    $currentThread.CurrentUICulture = $culture
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- "conda create -q -n script-environment python=%PYTHON_VERSION% selenium geckodriver firefox geopandas -c conda-forge"
- activate script-environment
- "pip install -r requirements.txt" 
- "SET PYTHONPATH=%PYTHONPATH%;%CD%"
- "python covid_19\\nl\\script.py .\\"
- powershell .\gitcommit.ps1
    